MuzON.Web/Models/ArtistViewModel.cs
using MuzON.Common.Common;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MuzON.Web.Models
{
    public class ArtistViewModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Name cannot be null!")]
        [Display(Name = "Artist full name")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Date cannot be null!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Artist birth date")]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Profile photo")]
        public string Image { get; set; }

        [Display(Name = "Country")]
        [Required(ErrorMessage = "Country cannot be null!")]
        public Guid CountryId { get; set; }
        public CountryViewModel Country { get; set; }

        [Display(Name = "Bands")]
        public List<Guid> SelectedBands { get; set; }

        public bool IsSelected { get; set; }
        [JsonIgnore]
        public ICollection<BandViewModel> Bands { get; set; }

        public ICollection<SongViewModel> Songs { get; set; }
    }
}

MuzON.Web/Controllers/ArtistsController.cs
using AutoMapper;
using MuzON.BLL.DTO;
using MuzON.BLL.Interfaces;
using MuzON.Web.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuzON.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class ArtistsController : BaseController
    {
        public ArtistsController(IArtistService artistServ,
                                ICountryService countryServ,
                                IBandService bandServ,
                                ISongService songServ)
            : base(bandServ, countryServ, artistServ, songServ) { }

        
        // GET: Artists
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetList()
        {
            var artists = Mapper.Map<IEnumerable<ArtistViewModel>>(
                                        artistService.GetArtists());
            foreach (var artist in artists)
            {
                artist.Bands = null;
                artist.Songs = null;
            }
            return Json(new { data = artists },JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(Guid id)
        {
            var artistDTO = artistService.GetArtistById(id);
            var artist = Mapper.Map<ArtistViewModel>(artistDTO);

            return PartialView("_DetailsPartial", artist);
        }

        public ActionResult Create()
        {
            var model = new ArtistViewModel
            {
                BirthDate = DateTime.Today
            };

            ViewBag.CountryId = util.GetSelectListItems<CountryDTO, CountryViewModel>(countryService.GetCountries());
            model.Bands = GetAllBands();

            // viewbag for post
            ViewBag.Action = "create";
            return PartialView("_CreateAndEditPartial", model);
        }

        [HttpPost]        
        [ValidateAntiForgeryToken]
        public JsonResult Create(ArtistViewModel artistViewModel)
        {
            if (ModelState.IsValid)
            {
                List<HttpPostedFileBase> songs = util.GetSongsFromRequest(Request.Files);
                var artistDTO = Mapper.Map<ArtistViewModel, ArtistDTO>(artistViewModel);
                artistDTO.Id = Guid.NewGuid();
                artistDTO.Image = util.SetImage(Request.Files["uploadImage"], artistDTO.Image);
                artistService.AddArtist(artistDTO);
                logger.InfoLog("Artist",
                            "created",
                            artistDTO.FullName,
                            artistDTO.Id,
                            User.Identity.Name);
                return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
            }
            ViewBag.CountryId = util.GetSelectListItems<CountryDTO, CountryViewModel>(countryService.GetCountries());
            return Json(new { artistViewModel, errorMessage = util.GetErrorList(ModelState.Values) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(Guid id)
        {
            var artist = artistService.GetArtistById(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            ArtistViewModel artistViewModel = Mapper.Map<ArtistViewModel>(artist);
            artistViewModel.Bands = GetAllBands(artist.Bands.Select(x => x.Id));
            ViewBag.CountryId = util.GetSelectListItems<CountryDTO, CountryViewModel>(countryService.GetCountries(), artistViewModel.CountryId);
           
            // viewbag for post
            ViewBag.Action = "edit";
            return PartialView("_CreateAndEditPartial", artistViewModel);
        }

        [HttpPost]        
        [ValidateAntiForgeryToken]
        public JsonResult Edit(ArtistViewModel artistViewModel)
        {

            if (ModelState.IsValid)
            {
                var artistDTO = Mapper.Map<ArtistViewModel, ArtistDTO>(artistViewModel);
                artistDTO.Image = util.SetImage(Request.Files["uploadImage"], artistDTO.Image, Request.Form["image"]);
                artistService.UpdateArtist(artistDTO);
                logger.InfoLog("Artist",
                            "edited",
                            artistDTO.FullName,
                            artistDTO.Id,
                            User.Identity.Name);
                return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
            }
            ViewBag.CountryId = util.GetSelectListItems<CountryDTO, CountryViewModel>(countryService.GetCountries(), artistViewModel.CountryId);

            return Json(new { artistViewModel, errorMessage = util.GetErrorList(ModelState.Values) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(Guid id)
        {
            var artist = artistService.GetArtistById(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            ArtistViewModel artistViewModel = Mapper.Map<ArtistViewModel>(artist);
            return PartialView("_DeletePartial", artistViewModel);
        }

        [HttpPost, ActionName("Delete")]        
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(Guid id)
        {
            var artistDTO = artistService.GetArtistById(id);
            artistService.DeleteArtist(artistDTO);
            logger.InfoLog("Artist",
                            "deleted",
                            artistDTO.FullName,
                            artistDTO.Id,
                            User.Identity.Name);
            return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
        }

        protected List<BandViewModel> GetAllBands(IEnumerable<Guid> selectedIds = null)
        {
            IEnumerable<BandDTO> bandDTOs = bandService.GetBands();

            IEnumerable<BandViewModel> bandModels = Mapper.Map<IEnumerable<BandViewModel>>(bandDTOs);

            if (selectedIds != null)
            {
                foreach (BandViewModel model in bandModels)
                {
                    model.IsSelected = selectedIds.Contains(model.Id);
                }
            }

            return bandModels.OrderBy(x => x.Name).ToList();
        }
    }
}

MuzON.Web/Views/Artists/Index.cshtml
@model IEnumerable<MuzON.Web.Models.ArtistViewModel>
@{
    ViewBag.Title = "Index";
}
<section class="portfolio-area section-gap" id="portfolio">
    <br />
    <br />
    <div class="container" id="addButton">
        <h2>Artists</h2>
    </div>
    <br />
    <div class="container">

        <table id="tableArtistsGrid" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0">
            <thead>
                <tr>
                    <th>Full Name</th>
                    <th>Country</th>
                    <th>Birth Date</th>
                    <th>Image</th>
                    <th>Actions</th>
                </tr>
            </thead>
        </table>
        <div class="container" id="addButton">
            <button type="button" class="btn btn-success btn-md" data-toggle="modal" data-url="@Url.Action("Create","Artists")" id="btnCreateArtist">
                <span class="fa fa-plus-circle" aria-hidden="true"></span> Add Artist
            </button>
        </div>
    </div>
</section>
<div class="modal fade" id="createArtistModal" tabindex="-1" role="dialog" aria-labelledby="CreateArtistModal" aria-hidden="true" data-backdrop="static">
    <div id="createArtistContainer">
    </div>
</div>

<div class="modal fade" id="editArtistModal" tabindex="-1" role="dialog" aria-labelledby="CreateArtistModal" aria-hidden="true" data-backdrop="static">
    <div id="editArtistContainer">
    </div>
</div>

<div class="modal fade" id="deleteArtistModal" tabindex="-1" role="dialog" aria-labelledby="DeleteArtistModal" aria-hidden="true" data-backdrop="static">
    <div id="deleteArtistContainer">
    </div>
</div>

<div class="modal fade" id="detailsArtistModal" tabindex="-1" role="dialog" aria-labelledby="DetailsArtistModal" aria-hidden="true" data-backdrop="static">
    <div id="detailsArtistContainer">
    </div>
</div>

<div class="modal fade" id="addSongArtistModal" tabindex="-1" role="dialog" aria-labelledby="AddSongArtistModal" aria-hidden="true" data-backdrop="static">
    <div id="addSongArtistContainer">
    </div>
</div>
@section scripts{
    <script src="~/Scripts/artistsGrid.js"></script>
}

MuzON.Web/Views/Artists/_CreateAndEditPartial.cshtml
@model MuzON.Web.Models.ArtistViewModel
@{
    /**/
    Layout = null;
}
@{
    if (ViewBag.Action == "create")
    {
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Artist</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                @using (Ajax.BeginForm("Create", null,
                    new AjaxOptions
                    {
                        HttpMethod = "Post",
                        OnSuccess = "CreateArtistSuccess(data)"
                    },
                    new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="modal-body">
                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.BirthDate, "{0:yyyy-MM-dd}", new { htmlAttributes = new { @class = "form-control date-picker" } })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    <div class="editor-field">
                                        <input class="form-control" type="file" id="uploadImage" name="uploadImage" accept="image/x-png,image/gif,image/jpeg" />
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Country", htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.DropDownList("CountryId", null, "Select country", htmlAttributes: new { @class = "chosen-select", @tabindex = "-1", @placeholder = "Select country" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.SelectedBands, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.ListBoxFor(model => model.SelectedBands,
                                           new MultiSelectList(Model.Bands, "Id", "Name"),
                                           htmlAttributes: new { @class = "chosen-select", @tabindex = "-1", @placeholder = "Select bands", multiple = "multiple" })
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="form-group">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <input type="submit" id="addAndEdit" class="btn btn-primary" value="Create" />
                            </div>
                        </div>

                    </div>
                }
            </div>

        </div>
    }


    else
    { <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Edit Artist</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                @using (Ajax.BeginForm("Edit", "Artists", null,
                new AjaxOptions
                {
                    HttpMethod = "Post",
                    OnSuccess = "UpdateArtistSuccess(data)"
                },
                new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="modal-body">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.BirthDate, "{0:yyyy-MM-dd}", new { htmlAttributes = new { @class = "form-control date-picker" } })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    <div class="editor-field">
                                        <img id="imageSize" src="data:image/jpeg;base64,@Model.Image" />
                                        <input type="hidden" name="image" value="@Model.Image" />
                                        <input class="form-control" type="file" id="uploadImage" name="uploadImage" accept="image/x-png,image/gif,image/jpeg" />
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Country", htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "chosen-select", @tabindex = "-1" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.SelectedBands, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.ListBoxFor(model => model.SelectedBands, 
                                           new MultiSelectList(Model.Bands, "Id", "Name", Model.Bands.Where(x=>x.IsSelected).Select(i=>i.Id)),
                                           htmlAttributes: new { @class = "chosen-select", @tabindex = "-1", multiple = "multiple" })
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <div class="form-group">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <input type="submit" class="btn btn-primary" value="Save" />
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>

    }

}

MuzON.Web/Views/Artists/_DeletePartial.cshtml
@model MuzON.Web.Models.ArtistViewModel
@{
    Layout = null;
}
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Delete Artist</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        </div>

        <div class="modal-body">
            <strong>Are you sure you want to delete this artist?</strong>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FullName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FullName)
                </dd>
            </dl>
            @using (Ajax.BeginForm("Delete", "Artists", null,
                new AjaxOptions
                {
                    HttpMethod = "Post",
                    OnSuccess = "DeleteArtistSuccess(data)"
                }, new { @class = "form-horizontal", role = "form" }))
            {

                <div class="form-actions no-color">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(x => x.Id)
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" value="Delete" class="btn btn-danger" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MuzON.Web/Views/Artists/_DetailsPartial.cshtml
@model MuzON.Web.Models.ArtistViewModel
@{
    Layout = null;
}
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Artist Details</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        </div>

        <div class="modal-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FullName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FullName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.BirthDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BirthDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Image)
                </dt>

                <dd>
                    <img id="imageSize" src="data:image/jpeg;base64,@Model.Image" />
                </dd>

                <dt>
                    <label>Country</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model=>model.Country.Name)
                </dd>

                <dt>
                    <label>Bands</label>
                </dt>
                @if (Model.Bands.Count >= 1)
                {
                    foreach (var item in Model.Bands)
                    {
                        <dd>
                            - @item.Name
                        </dd>
                    }
                }
                else
                {
                    <dd>
                        <strong>No Bands</strong>
                    </dd>
                }

            </dl>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

MuzON.Web/Views/Artists/_Partial.cshtml
@model MuzON.Web.Models.ArtistViewModel
@{
    Layout = null;
}

<div class="container" id="small-dialog">
    <div class="row">
        <div class="col-md-12 text-center">
            <h3><strong>Artist details page</strong></h3>
            <hr />
        </div>
        @* Image *@
        <div class="col-md-4 imageClass">
            <h3><strong>Photo</strong></h3>
            <a href="data:image/jpeg;base64,@Model.Image" class="see-img">
                <img class="image img-fluid" src="data:image/jpeg;base64,@Model.Image" style="width: auto; display: inline-block;" />
            </a>
        </div>
        <br />
        @* Info *@
        <div class="col-md-4">
            <h3><strong>Info</strong></h3>
            <ul class="unordered-list">
                <li><strong>Artist full name:</strong> @Html.DisplayFor(model => model.FullName)</li>
                <li><strong>Country name:</strong> @Html.DisplayFor(model => model.Country.Name)</li>
                <li><strong>Birth date:</strong> @Html.DisplayFor(model => model.BirthDate)</li>

            </ul>
        </div>
        @* Bands *@
        <div class="col-md-4">
            <h3><strong>Bands</strong></h3>
            <ul class="unordered-list">
                @if (Model.Bands != null && Model.Bands.Count > 0)
                {
                    foreach (var band in Model.Bands)
                    {
                        <li>@band.Name</li>
                    }
                }
                else
                {
                    <li>No bands</li>
                }
            </ul>
        </div>
        <div class="col-md-12"><br /><hr></div>
        @* Songs *@
        <div class="col-md-12 text-center">
            <h3><strong>Songs</strong></h3>
            <ul>
                @if (Model.Songs != null && Model.Songs.Count > 0)
                {
                    foreach (var song in Model.Songs)
                    {
                <li>
                    <hr />
                    <p>@song.Name</p>
                    <audio controls preload="metadata">
                        <source src="@Url.Content("/songs/"+ song.Id +"/" + song.FileName)" type="audio/mp3">
                    </audio>
                </li>
                
                    }
                }
                else
                {
                    <li>
                        No songs
                    </li>
                }
            </ul>
        </div>
        <div class="col-md-12"><hr></div>
        @* Comments *@
        <div class="col-md-12 text-center">
            <p>Here will be comments.</p>
        </div>
    </div>
</div>
@section scripts{
<script>
    $(document).ready(function () {
        $('audio').mediaelementplayer();
    });
</script>    
}