MuzON.Web/Controllers/BandsController.cs
using AutoMapper;
using MuzON.BLL.DTO;
using MuzON.BLL.Interfaces;
using MuzON.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuzON.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class BandsController : BaseController
    {
        public BandsController(IBandService artistServ, 
                                ICountryService countryServ, 
                                IArtistService bandServ,
                                ISongService songServ)
            : base(artistServ, countryServ, bandServ, songServ) { }

        // GET: Bands
        public ActionResult Index()
        {
            return View();
        }
        
        public JsonResult GetList()
        {
            var bands = Mapper.Map<IEnumerable<BandViewModel>>(
                                                bandService.GetBands());
            foreach (var band in bands)
            {
                band.Artists = null;
            }
            return Json(new { data = bands }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(Guid id)
        {
            var bandDTO = bandService.GetBandById(id);
            var band = Mapper.Map<BandViewModel>(bandDTO);
            return PartialView("_DetailsPartial", band);
        }
        
        public ActionResult Create()
        {
            var model = new BandViewModel
            {
                CreatedDate = DateTime.Today
            };

            ViewBag.CountryId = util.GetSelectListItems<CountryDTO, CountryViewModel>(countryService.GetCountries());
            model.Artists = GetAllArtists();
            
            // viewbag for post
            ViewBag.Action = "create";
            return PartialView("_CreateAndEditPartial", model);
        }

        [HttpPost]        
        [ValidateAntiForgeryToken]
        public JsonResult Create(BandViewModel bandViewModel)
        {
            if (ModelState.IsValid)
            {
                var bandDTO = Mapper.Map<BandDTO>(bandViewModel);
                bandDTO.Id = Guid.NewGuid();

                bandDTO.Image = util.SetImage(Request.Files["uploadImage"], bandDTO.Image);
                bandService.AddBand(bandDTO);
                logger.InfoLog("Band",
                            "created",
                            bandDTO.Name,
                            bandDTO.Id,
                            User.Identity.Name);
                return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
            }
            ViewBag.CountryId = util.GetSelectListItems<CountryDTO, CountryViewModel>(countryService.GetCountries());
            return Json(new { bandViewModel, errorMessage = util.GetErrorList(ModelState.Values) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(Guid id)
        {
            var band = bandService.GetBandById(id);

            if (band == null)
            {
                return HttpNotFound();
            }

            BandViewModel bandViewModel = Mapper.Map<BandViewModel>(band);
            bandViewModel.Artists = GetAllArtists(band.Artists.Select(x=>x.Id));
            ViewBag.CountryId = util.GetSelectListItems<CountryDTO, CountryViewModel>(countryService.GetCountries(), bandViewModel.CountryId);

            // viewbag for post
            ViewBag.Action = "edit";
            return PartialView("_CreateAndEditPartial", bandViewModel);
        }

        [HttpPost]        
        [ValidateAntiForgeryToken]
        public JsonResult Edit(BandViewModel bandViewModel)
        {

            if (ModelState.IsValid)
            {
                var bandDTO = Mapper.Map<BandViewModel, BandDTO>(bandViewModel);
                bandDTO.Image = util.SetImage(Request.Files["uploadImage"], bandDTO.Image, Request.Form["image"]);
                bandService.UpdateBand(bandDTO);
                logger.InfoLog("Band",
                            "edited",
                            bandDTO.Name,
                            bandDTO.Id,
                            User.Identity.Name);
                return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
            }
            ViewBag.CountryId = util.GetSelectListItems<CountryDTO, CountryViewModel>(countryService.GetCountries(), bandViewModel.CountryId);
            return Json(new { bandViewModel, errorMessage = util.GetErrorList(ModelState.Values) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(Guid id)
        {
            var band = bandService.GetBandById(id);
            if (band == null)
            {
                return HttpNotFound();
            }
            BandViewModel bandViewModel = Mapper.Map<BandViewModel>(band);
            return PartialView("_DeletePartial", bandViewModel);
        }

        [HttpPost, ActionName("Delete")]        
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(Guid id)
        {
            var bandDTO = bandService.GetBandById(id);
            bandService.DeleteBand(bandDTO);
            logger.InfoLog("Band",
                            "deleted",
                            bandDTO.Name,
                            bandDTO.Id,
                            User.Identity.Name);
            return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
        }

        protected List<ArtistViewModel> GetAllArtists(IEnumerable<Guid> selectedIds = null)
        {
            IEnumerable<ArtistDTO> artistDTOs = artistService.GetArtists();

            IEnumerable<ArtistViewModel> artistModels = Mapper.Map<IEnumerable<ArtistViewModel>>(artistDTOs);

            if (selectedIds != null)
            {
                foreach (ArtistViewModel model in artistModels)
                {
                    model.IsSelected = selectedIds.Contains(model.Id);
                }
            }

            return artistModels.OrderBy(x => x.FullName).ToList();
        }
    }
}

MuzON.Web/Controllers/SongsController.cs
using AutoMapper;
using MuzON.BLL.DTO;
using MuzON.BLL.Interfaces;
using MuzON.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuzON.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class SongsController : BaseController
    {
        public SongsController(IBandService bandServ,
            ICountryService countryServ,
            IArtistService artistServ,
            ISongService songServ,
            IGenreService genreServ)
            : base(bandServ, countryServ, artistServ, songServ, genreServ) { }

        // GET: Songs
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetList()
        {
            var songs = Mapper.Map<IEnumerable<SongViewModel>>(songService.GetSongs());

            return Json(new { data = songs }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(Guid id)
        {
            var songDTO = songService.GetSongById(id);
            var song = Mapper.Map<SongViewModel>(songDTO);
            song.Artists = GetAllArtists(songDTO.Artists.Select(x => x.Id)).Where(x => x.IsSelected).ToList();
            song.Bands = GetAllBands(songDTO.Bands.Select(x => x.Id)).Where(x => x.IsSelected).ToList();
            song.Genres = GetAllGenres(songDTO.Genres.Select(x => x.Id)).Where(x=>x.IsSelected).ToList();
            return PartialView("_DetailsPartial", song);
        }

        public ActionResult Create()
        {
            var song = new SongViewModel
            {
                Artists = GetAllArtists(),
                Bands = GetAllBands(),
                Genres = GetAllGenres()
            };
            ViewBag.Action = "create";
            return PartialView("_CreateAndEditPartial", song);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(SongViewModel songViewModel)
        {
            if (ModelState.IsValid)
            {
                songViewModel.Artists = GetAllArtists(songViewModel.SelectedArtists).Where(x=>x.IsSelected).ToList();
                songViewModel.Bands = GetAllBands(songViewModel.SelectedBands).Where(x => x.IsSelected).ToList();
                songViewModel.Genres = GetAllGenres(songViewModel.SelectedGenres).Where(x => x.IsSelected).ToList();
                List<HttpPostedFileBase> songs = util.GetSongsFromRequest(Request.Files);
                foreach (var song in songs)
                {
                    songViewModel.Id = Guid.NewGuid();
                    songViewModel.FileName = song.FileName;
                    var songDTO = Mapper.Map<SongDTO>(songViewModel);
                    songService.AddSong(songDTO);
                    SaveSong(song, songDTO.Id);
                    logger.InfoLog("Song",
                            "added",
                            songDTO.FileName,
                            songDTO.Id,
                            User.Identity.Name);
                }
                return Json(new { data = "success" });
            }
            return Json(new { songViewModel, errorMessage = util.GetErrorList(ModelState.Values) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(Guid id)
        {
            var songDTO = songService.GetSongById(id);
            var song = Mapper.Map<SongViewModel>(songDTO);
            song.Artists = GetAllArtists(songDTO.Artists.Select(x => x.Id));
            song.Bands = GetAllBands(songDTO.Bands.Select(x => x.Id));
            song.Genres = GetAllGenres(songDTO.Genres.Select(x => x.Id));
            ViewBag.Action = "edit";
            return PartialView("_CreateAndEditPartial", song);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(SongViewModel songViewModel)
        {
            if (ModelState.IsValid)
            {
                List<HttpPostedFileBase> songs = util.GetSongsFromRequest(Request.Files);
                songViewModel.Artists = GetAllArtists(songViewModel.SelectedArtists).Where(x => x.IsSelected).ToList();
                songViewModel.Bands = GetAllBands(songViewModel.SelectedBands).Where(x => x.IsSelected).ToList();
                songViewModel.Genres = GetAllGenres(songViewModel.SelectedGenres).Where(x => x.IsSelected).ToList();
                var songDTO = Mapper.Map<SongDTO>(songViewModel);
                songService.UpdateSong(songDTO);
                logger.InfoLog("Song",
                            "edited",
                            songDTO.FileName,
                            songDTO.Id,
                            User.Identity.Name);
                foreach (var song in songs)
                {
                    SaveSong(song, songDTO.Id);
                }
                return Json(new { data = "success" });
            }
            return Json(new { songViewModel, errorMessage = util.GetErrorList(ModelState.Values) }, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult Delete(Guid id)
        {
            var song = songService.GetSongById(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            var songViewModel = Mapper.Map<SongViewModel>(song);
            return PartialView("_DeletePartial", songViewModel);
        }

        [HttpPost, ActionName("Delete")]        
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(Guid id)
        {
            var songDTO = songService.GetSongById(id);
            songService.DeleteSong(songDTO);
            DeleteSong(songDTO.Id);
            logger.InfoLog("Song",
                            "edited",
                            songDTO.FileName,
                            songDTO.Id,
                            User.Identity.Name);
            return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
        }

        protected List<ArtistViewModel> GetAllArtists(IEnumerable<Guid> selectedIds = null)
        {
            IEnumerable<ArtistDTO> artistDTOs = artistService.GetArtists();

            IEnumerable<ArtistViewModel> artistModels = Mapper.Map<IEnumerable<ArtistViewModel>>(artistDTOs);

            if (selectedIds != null)
            {
                foreach (ArtistViewModel model in artistModels)
                {
                    model.IsSelected = selectedIds.Contains(model.Id);
                }
            }

            return artistModels.OrderBy(x => x.FullName).ToList();
        }

        protected List<BandViewModel> GetAllBands(IEnumerable<Guid> selectedIds = null)
        {
            IEnumerable<BandDTO> bandDTOs = bandService.GetBands();

            IEnumerable<BandViewModel> bandModels = Mapper.Map<IEnumerable<BandViewModel>>(bandDTOs);

            if (selectedIds != null)
            {
                foreach (BandViewModel model in bandModels)
                {
                    model.IsSelected = selectedIds.Contains(model.Id);
                }
            }

            return bandModels.OrderBy(x => x.Name).ToList();
        }

        protected List<GenreViewModel> GetAllGenres(IEnumerable<Guid> selectedIds = null)
        {
            IEnumerable<GenreDTO> genreDTOs = genreService.GetGenres();

            IEnumerable<GenreViewModel> genreModels = Mapper.Map<IEnumerable<GenreViewModel>>(genreDTOs);

            if (selectedIds != null)
            {
                foreach (GenreViewModel model in genreModels)
                {
                    model.IsSelected = selectedIds.Contains(model.Id);
                }
            }

            return genreModels.OrderBy(x => x.Name).ToList();
        }
    }
}

MuzON.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="icon" type="image/png" href="~/favicon.ico" />
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>MuzON - портал бесплатной музыки</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!-- CSS -->
    <link href="/Content/linearicons.css" rel="stylesheet" />
    <link href="/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="/Content/bootstrap.css" rel="stylesheet" />
    <link href="/Content/magnific-popup.css" rel="stylesheet" />
    <link href="~/Content/nice-select.css" rel="stylesheet" />
    <link href="/Content/animate.min.css" rel="stylesheet" />
    <link href="/Content/owl.carousel.css" rel="stylesheet" />
    <link rel="stylesheet" href="/Content/chosen/chosen.css">
    <link href="/Content/main.css" rel="stylesheet" />
    <link href="/Content/DataTables/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="/Content/DataTables/css/responsive.bootstrap4.min.css" rel="stylesheet" />
    <script src="/Scripts/jquery-3.3.1.min.js"></script>
    <script src="/Scripts/jquery.dataTables.min.js"></script>
    <script src="/Scripts/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
</head>
<body>
    <header id="header">
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo">
                    <a href="@Url.Action("Index", "Home")"><h3>MuzON</h3></a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        @Html.Partial("_PartialLogin")
                    </ul>
                </nav><!-- #nav-menu-container -->
            </div>
        </div>
    </header><!-- #header -->
    @RenderBody()
    <!-- start footer Area -->
    <footer class="footer footer-area section-gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="single-footer-widget">
                        <h4>About MuzON</h4>
                        <p>
                            It's a free platform where you can listening free musik.
                        </p>
                        <p class="footer-text">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            &copy; @DateTime.Now.Year - MuzON
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->

    <script src="/Scripts/umd/popper.min.js"></script>
    <script src="/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-multiselect.js"></script>
    <link href="~/Content/bootstrap-multiselect.css" />
    <script src="/Scripts/easing.min.js"></script>
    <script src="/Scripts/hoverIntent.js"></script>
    <script src="/Scripts/superfish.min.js"></script>
    <script src="~/Scripts/jquery.ajaxchimp.min.js"></script>
    <script src="/Scripts/jquery.magnific-popup.min.js"></script>
    <script src="/Scripts/jquery.tabs.min.js"></script>
    <script src="/Scripts/jquery.nice-select.min.js"></script>
    <script src="/Scripts/isotope.pkgd.min.js"></script>
    <script src="/Scripts/jquery.counterup.min.js"></script>
    <script src="/Scripts/simple-skillbar.js"></script>
    <script src="/Scripts/owl.carousel.min.js"></script>
    <script src="/Scripts/main.js"></script>
    <script src="/Content/chosen/chosen.jquery.js" type="text/javascript"></script>
    <script src="~/Content/bootstrap-notify/bootstrap-notify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

MuzON.Web/Views/Shared/_PartialLogin.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
        <li><a href="@Url.Action("Index", "Playlists")">Playlists</a></li>
        if (User.IsInRole("admin"))
        {
            <li><a href="@Url.Action("Index", "Artists")">Artists</a></li>
            <li><a href="@Url.Action("Index", "Bands")">Bands</a></li>
            <li><a href="@Url.Action("Index", "Songs")">Songs</a></li>
            <li><a href="@Url.Action("Index", "Account")">Users</a></li>
        }
        <li>
            <a href="@Url.Action("ChangePassword", "Account")">Hello @User.Identity.GetUserName()!</a>
        </li>
        <li>
            <a href="javascript:document.getElementById('logoutForm').submit()">
                Log out
            </a>
        </li>

    }
}
else
{
        <form>
            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
            <li><a href="@Url.Action("Index", "Playlists")">Playlists</a></li>
            <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
        </form>
}