MuzON.Web/Models/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MuzON.Web.Models
{
    public class CommentViewModel
    {
        public Guid Id { get; set; }
        public string Text { get; set; }
        public Guid? SongId { get; set; }
        public Guid UserId { get; set; }
        public Guid? PlaylistId { get; set; }
    }
}

MuzON.Web/Models/PlaylistViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MuzON.Web.Models
{
    public class PlaylistViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Index { get; set; }
        public List<Guid> SelectedSongs { get; set; }
        public double Rating { get; set; }
        public ICollection<SongViewModel> Songs { get; set; }
        public ICollection<CommentViewModel> Comments { get; set; }
    }
}

MuzON.Web/Controllers/PlaylistsController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using MuzON.BLL.DTO;
using MuzON.BLL.Interfaces;
using MuzON.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MuzON.Web.Controllers
{
    public class PlaylistsController : BaseController
    {
        public PlaylistsController(IGenreService genre, IPlayListService playList, ISongService song, ICommentService comment)
            : base(genre, playList, song, comment)
        { }

        // GET: Playlists
        public ActionResult Index()
        {
            var playlistDTOs = playListService.GetPlaylists();
            var playlists = Mapper.Map<IEnumerable<PlaylistViewModel>>(playlistDTOs);
            foreach (var item in playlists)
            {
                foreach (var item2 in playlistDTOs.Where(x => x.Id == item.Id).ToList().Select(x => x.Songs).ToList())
                {
                    item.Songs = Mapper.Map<List<SongViewModel>>(item2.ToList());
                    item.Rating = playListService.PlaylistRating(item.Id);
                }
            }
            return View(playlists);
        }

        public ActionResult Details(Guid id)
        {
            var playlistDTO = playListService.GetPlaylistById(id);
            var playlist = Mapper.Map<PlaylistViewModel>(playlistDTO);
            playlist.Rating = playListService.PlaylistRatingFromUser(playlist.Id, Guid.Parse(User.Identity.GetUserId()));
            playlist.Songs = GetAllSongs(playlistDTO.Songs.Select(x => x.Id)).Where(x => x.IsSelected).ToList();
            return PartialView("_Details", playlist);
        }

        public ActionResult Create()
        {
            var playlist = new PlaylistViewModel
            {
                Image = String.Empty,
                Songs = GetAllSongs()
            };
            return PartialView("_PlaylistAction", playlist);
        }

        public ActionResult Edit(Guid id)
        {
            var playlist = playListService.GetPlaylistById(id);
            if (playlist == null)
            {
                return HttpNotFound();
            }
            PlaylistViewModel playlistViewModel = Mapper.Map<PlaylistViewModel>(playlist);
            playlistViewModel.Songs = GetAllSongs(playlist.Songs.Select(x => x.Id));
            return PartialView("_PlaylistAction", playlistViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreateEdit(PlaylistViewModel playlistViewModel)
        {
            if (ModelState.IsValid)
            {
                playlistViewModel.Comments = playlistViewModel.Id == Guid.Parse("00000000-0000-0000-0000-000000000000") 
                                             ? null 
                                             : GetAllComments(playlistViewModel.Id);
                playlistViewModel.Songs = GetAllSongs(playlistViewModel.SelectedSongs).Where(x => x.IsSelected).ToList();
                var playlist = Mapper.Map<PlaylistDTO>(playlistViewModel);
                if(playlist.Id == Guid.Parse("00000000-0000-0000-0000-000000000000"))
                {
                    playlist.Id = Guid.NewGuid();
                    playlist.Image = util.SetImage(Request.Files["uploadImage"], playlist.Image);
                    playListService.AddPlayList(playlist);
                    logger.InfoLog("Playlist",
                                "added",
                                playlist.Name,
                                playlist.Id,
                                User.Identity.Name);
                    return Json(new { data = "success" });
                }
                else
                {
                    playlist.Image = util.SetImage(Request.Files["uploadImage"], playlist.Image, Request.Form["image"]);
                    playListService.UpdatePlaylist(playlist);
                    logger.InfoLog("Playlist",
                                "edited",
                                playlist.Name,
                                playlist.Id,
                                User.Identity.Name);
                    return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { playlistViewModel, errorMessage = util.GetErrorList(ModelState.Values) }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AddComment(Guid id)
        {
            var playlist = playListService.GetPlaylistById(id);
            if (playlist != null)
            {
                var userId = User.Identity.GetUserId();
                var text = Request.Form["text"];
                SaveComment(Guid.Parse(userId), text, null, id);
                GetComments(id);
                return Json(new { data = "success", id });
            }
            return Json(new { playlist, errorMessage = util.GetErrorList(ModelState.Values) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetComments(Guid id)
        {
            var playlist = playListService.GetPlaylistById(id);
            return PartialView("_Comments", Mapper.Map<PlaylistViewModel>(playlist));
        }

        public JsonResult RatePlaylist(Guid id, string ratingFromUser)
        {
            var playlist = playListService.GetPlaylistById(id);
            if (playlist != null)
            {
                var userId = User.Identity.GetUserId();
                var rate = double.Parse(ratingFromUser.Replace('.', ','));
                var rating = new RatingViewModel
                {
                    Id = Guid.NewGuid(),
                    UserId = Guid.Parse(userId),
                    Value = rate,
                    SongId = null,
                    PlaylistId = playlist.Id
                };
                var ratingDto = Mapper.Map<RatingDTO>(rating);
                playListService.RatePlayList(ratingDto);
                return Json(new { data = "success", id });
            }
            return Json(new { playlist, errorMessage = util.GetErrorList(ModelState.Values) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(Guid id)
        {
            var playlist = playListService.GetPlaylistById(id);
            if (playlist == null)
            {
                return HttpNotFound();
            }
            PlaylistViewModel playlistViewModel = Mapper.Map<PlaylistViewModel>(playlist);
            return PartialView("_Delete", playlistViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(Guid id)
        {
            var playlist = playListService.GetPlaylistById(id);
            playListService.DeletePlaylist(playlist);
            logger.InfoLog("Playlist",
                            "deleted",
                            playlist.Name,
                            playlist.Id,
                            User.Identity.Name);
            return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
        }

        protected List<SongViewModel> GetAllSongs(IEnumerable<Guid> selectedIds = null)
        {
            IEnumerable<SongDTO> songDTOs = songService.GetSongs();

            IEnumerable<SongViewModel> songViewModels = Mapper.Map<IEnumerable<SongViewModel>>(songDTOs);

            if (selectedIds != null)
            {
                foreach (SongViewModel model in songViewModels)
                {
                    model.IsSelected = selectedIds.Contains(model.Id);
                }
            }

            return songViewModels.OrderBy(x => x.Name).ToList();
        }

        protected List<CommentViewModel> GetAllComments(Guid? playlistId = null)
        {
            IEnumerable<CommentDTO> commentDTOs = playlistId == null
                                        ? commentService.GetComments()
                                        : commentService.GetCommentsByPlaylistId(playlistId.Value);

            IEnumerable<CommentViewModel> commentViewModels = Mapper.Map<IEnumerable<CommentViewModel>>(commentDTOs);

            return commentViewModels.ToList();
        }
    }
}

MuzON.Web/Views/Playlists/Index.cshtml
@model IEnumerable<MuzON.Web.Models.PlaylistViewModel>
@{
    ViewBag.Title = "Index";
}
<section class="portfolio-area section-gap" id="portfolio">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">
                    <h1 class="mb-10">All Playlists</h1>
                    <p>You can add your playlist.</p>
                </div>
            </div>
        </div>
        <div class="filters">
            <button type="button" class="genric-btn success radius" data-toggle="modal" data-url="@Url.Action("Create", "Playlists")" id="btnCreatePlayList">
                <span class="fa fa-plus-circle" aria-hidden="true"></span> Add Playlist
            </button>
        </div>
        <div class="filters-content">
            <div class="row grid">
                @foreach (var item in Model)
                {
                    <div class="single-portfolio col-sm-4 all artist">
                        <div class="relative">
                            <div class="thumb">
                                <div class="overlay overlay-bg"></div>
                                <img class="image img-fluid rounded" src="data:image/jpeg;base64,@item.Image" alt="">
                            </div>
                            <a href="@Url.Action("Details","Playlists", new { id = item.Id})" class="img-pop-up">
                                <div class="middle" style="left: 35%;">
                                    <div class="text align-self-center d-flex"><img src="@Url.Content("~/Content/images/preview.png")" alt=""></div>
                                </div>
                            </a>
                            <a href="data:image/jpeg;base64,@item.Image" class="see-img">
                                <div class="middle" style="left: 65%;">
                                    <div class="text align-self-center d-flex"><i class="fa fa-file-image-o"></i></div>
                                </div>
                            </a>
                        </div>
                        <div class="p-inner">
                            <h4>@item.Name</h4>
                            <div class="cat">@item.Songs.Count - Songs in playlist | @item.Comments.Count - Comments | Rate - @Math.Round(item.Rating, 1)</div>
                            <button type="button" class="genric-btn primary radius" data-toggle="modal" data-url="@Url.Action("Edit","Playlists", new { id = item.Id})" id="btnCreatePlayList">
                                <span class="fa fa-pencil-square-o" aria-hidden="true"></span> Edit
                            </button>

                            <button type="button" class="genric-btn danger radius" data-toggle="modal" data-url="@Url.Action("Delete","Playlists", new { id = item.Id})" id="btnDeletePlaylist">
                                <span class="fa fa-trash" aria-hidden="true"></span> Delete
                            </button>
                        </div>
                        
                    </div>

                }
                @if (Model == null || !(Model.Count() > 0))
                {
                    <div class="single-portfolio col-sm-12 all text-center">
                        <h3>No playlists</h3>
                    </div>
                }
            </div>
        </div>

    </div>
</section>

<div class="modal fade" id="createPlayListModal" tabindex="-1" role="dialog" aria-labelledby="CreatePlayListModal" aria-hidden="true" data-backdrop="static">
    <div id="createPlayListContainer">
    </div>
</div>

<div class="modal fade" id="deletePlayListModal" tabindex="-1" role="dialog" aria-labelledby="DeletePlayListModal" aria-hidden="true" data-backdrop="static">
    <div id="deletePlayListContainer">
    </div>
</div>

MuzON.Web/Views/Playlists/_Comments.cshtml
@model MuzON.Web.Models.PlaylistViewModel


<ul class="unordered-list partial">
    @if (Model.Comments.Count > 0)
    {
        foreach (var item in Model.Comments)
        {
            <li>@item.Text</li>
        }
    }
    else
    {
        <li>No comments</li>
    }
</ul>

MuzON.Web/Views/Playlists/_Delete.cshtml
@model MuzON.Web.Models.PlaylistViewModel
@{
    Layout = null;
}
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Delete Playlist</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        </div>

        <div class="modal-body">
            <strong>Are you sure you want to delete this playlist?</strong>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>
            @using (Ajax.BeginForm("Delete", "Playlists", null,
                new AjaxOptions
                {
                    HttpMethod = "Post",
                    OnSuccess = "DeletePlaylistSuccess(data)"
                }, new { @class = "form-horizontal", role = "form" }))
            {

                <div class="form-actions no-color">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(x => x.Id)
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" value="Delete" class="btn btn-danger" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MuzON.Web/Views/Playlists/_Details.cshtml
@model MuzON.Web.Models.PlaylistViewModel
@{
    Layout = null;
}

<div class="container" id="small-dialog">
    <div class="row">
        <div class="col-md-12 text-center">
            <input type="hidden" name="id" id="modelId" value="@Model.Id" />
            <h3><strong>Playlist details page</strong></h3>
            <hr />
        </div>
        @* Image *@
        <div class="col-md-6 imageClass">
            <h3><strong>Photo</strong></h3>
            <a href="data:image/jpeg;base64,@Model.Image" class="see-img">
                <img class="image img-fluid" src="data:image/jpeg;base64,@Model.Image" style="width: auto; display: inline-block;" />
            </a>
        </div>
        <br />
        @* Info *@
        <div class="col-md-6">
            <h3><strong>Rate this</strong></h3>
            <div id="rateYo"></div>
            <div>
                <button id="getRating">Rate</button>
            </div>
            <h3><strong>Info</strong></h3>
            <ul class="unordered-list">
                <li><strong>Playlist name:</strong> @Html.DisplayFor(model => model.Name)</li>
            </ul>
        </div>
        <div class="col-md-12"><br /><hr></div>
        @* Songs *@
        <div class="col-md-12 text-center">
            <h3><strong>Songs</strong></h3>
            <ul>
                @if (Model.Songs != null && Model.Songs.Count > 0)
                {
                    foreach (var song in Model.Songs)
                    {
                        <li>
                            <hr />
                            <p>@song.Name</p>
                            <audio controls preload="metadata">
                                <source src="@Url.Content("/songs/"+ song.Id +"/" + song.FileName)" type="audio/mp3">
                            </audio>
                        </li>

                    }
                }
                else
                {
                    <li>
                        No songs
                    </li>
                }
            </ul>
        </div>
        <div class="col-md-12"><hr></div>
        @* Comments *@

        <div class="col-md-12 text-center">
            @{Html.RenderPartial("_Comments", Model);}
            <hr />
            <p><strong>Add comment</strong></p>
            @using (Ajax.BeginForm("AddComment", new { id = Model.Id },
            new AjaxOptions
            {
                HttpMethod = "Post",
                OnSuccess = "AddComment(data)"
            },
            new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-12">
                            <textarea class="form-control" rows="5" id="text" name="text" placeholder="Type your comment..." required></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" id="addAndEdit" class="btn btn-primary" value="Add" />
                    </div>
                </div>
            }

        </div>
    </div>
    <script>
        $(document).ready(
            $(function () {
                var rate = parseFloat(@Model.Rating.ToString().Replace(',','.'));
                if (rate > 0) {
                    $("#rateYo").rateYo({
                        rating: rate,
                        readOnly: true
                    });
                    $('#getRating').hide();
                    return;
                }
                var $rateYo = $("#rateYo").rateYo({
                    precision: 2,
                    maxValue: 5,
                    numStars: 5,
                    "rating": rate
                });
                /* set the option `multiColor` to show Multi Color Rating */
                $rateYo.rateYo("option", "multiColor", true);
                var id = $('#modelId').val();


                $("#getRating").click(function () {
                    /* post rating */
                    var rating = $rateYo.rateYo("rating");
                    console.log(rating);
                    $.ajax({
                        url: "/Playlists/RatePlaylist/" + id,
                        type: "POST",
                        data: {
                            "ratingFromUser": rating
                        },
                        cache: false,
                        success: function (data) {
                            if (data.data == "success") {
                                $.notify({
                                    // options
                                    icon: 'fa fa-success',
                                    title: '<strong>Success</strong>: ',
                                    message: "You successfully rated this playlist!"
                                }, {
                                        type: 'success',
                                        z_index: 1051,
                                        animate: {
                                            enter: 'animated bounceIn',
                                            exit: 'animated bounceOut'
                                        }
                                    });
                                $('#small-dialog').load("/Playlists/Details/" + data.id);
                                return;
                            }
                        }
                    });
                });
            }));
    </script>
</div>

MuzON.Web/Views/Playlists/_PlaylistAction.cshtml
@model MuzON.Web.Models.PlaylistViewModel
@{
    /**/
    Layout = null;
}
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Add Artist</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        </div>
        @using (Ajax.BeginForm("CreateEdit", null,
            new AjaxOptions
            {
                HttpMethod = "Post",
                OnSuccess = "CreatePlaylistSuccess(data)"
            },
            new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x=>x.Id)
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            <div class="editor-field">
                                @if (Model.Image != String.Empty)
                                {
                                    <img id="imageSize" src="data:image/jpeg;base64,@Model.Image" />
                                    <input type="hidden" name="image" value="@Model.Image" />
                                }
                                <input class="form-control" type="file" id="uploadImage" name="uploadImage" accept="image/x-png,image/gif,image/jpeg" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Songs, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.ListBoxFor(model => model.SelectedSongs,
                                   new MultiSelectList(Model.Songs, "Id", "Name", Model.Songs.Where(x=>x.IsSelected).Select(x=>x.Id)),
                                   htmlAttributes: new { @class = "chosen-select", @tabindex = "-1", @placeholder = "Select bands", multiple = "multiple" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" id="addAndEdit" class="btn btn-primary" value="Create" />
                    </div>
                </div>

            </div>
        }
    </div>

</div>